# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorizationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorizationWindow(object):
    def setupUi(self, authorizationWindow):
        authorizationWindow.setObjectName("authorizationWindow")
        authorizationWindow.resize(219, 294)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        authorizationWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(authorizationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.guestButton = QtWidgets.QPushButton(self.centralwidget)
        self.guestButton.setGeometry(QtCore.QRect(30, 20, 161, 41))
        self.guestButton.setObjectName("guestButton")
        self.userButton = QtWidgets.QPushButton(self.centralwidget)
        self.userButton.setGeometry(QtCore.QRect(30, 70, 161, 41))
        self.userButton.setObjectName("userButton")
        self.waiterButton = QtWidgets.QPushButton(self.centralwidget)
        self.waiterButton.setGeometry(QtCore.QRect(30, 120, 161, 41))
        self.waiterButton.setObjectName("waiterButton")
        self.cookButton = QtWidgets.QPushButton(self.centralwidget)
        self.cookButton.setGeometry(QtCore.QRect(30, 170, 161, 41))
        self.cookButton.setObjectName("cookButton")
        self.adminButton = QtWidgets.QPushButton(self.centralwidget)
        self.adminButton.setGeometry(QtCore.QRect(30, 220, 161, 41))
        self.adminButton.setObjectName("adminButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 260, 161, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        authorizationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(authorizationWindow)
        self.statusbar.setObjectName("statusbar")
        authorizationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(authorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(authorizationWindow)

    def retranslateUi(self, authorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        authorizationWindow.setWindowTitle(_translate("authorizationWindow", "Авторизація"))
        self.guestButton.setText(_translate("authorizationWindow", "Гість"))
        self.userButton.setText(_translate("authorizationWindow", "Користувач"))
        self.waiterButton.setText(_translate("authorizationWindow", "Офіціант"))
        self.cookButton.setText(_translate("authorizationWindow", "Кухар"))
        self.adminButton.setText(_translate("authorizationWindow", "Адміністратор"))
