# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cartWindow(object):
    def setupUi(self, cartWindow):
        cartWindow.setObjectName("cartWindow")
        cartWindow.resize(519, 370)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        cartWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(cartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 260, 161, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.dishesArea = QtWidgets.QScrollArea(self.centralwidget)
        self.dishesArea.setGeometry(QtCore.QRect(10, 10, 271, 291))
        self.dishesArea.setWidgetResizable(True)
        self.dishesArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dishesArea.setObjectName("dishesArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 269, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.l = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.l.setObjectName("l")
        self.dishesArea.setWidget(self.scrollAreaWidgetContents)
        self.amountLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountLabel.setGeometry(QtCore.QRect(10, 310, 81, 21))
        self.amountLabel.setObjectName("amountLabel")
        self.dishesDeleteButtonsArea = QtWidgets.QScrollArea(self.centralwidget)
        self.dishesDeleteButtonsArea.setGeometry(QtCore.QRect(290, 10, 221, 291))
        self.dishesDeleteButtonsArea.setWidgetResizable(True)
        self.dishesDeleteButtonsArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dishesDeleteButtonsArea.setObjectName("dishesDeleteButtonsArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 219, 289))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.l_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.l_2.setObjectName("l_2")
        self.dishesDeleteButtonsArea.setWidget(self.scrollAreaWidgetContents_2)
        self.orderButton = QtWidgets.QPushButton(self.centralwidget)
        self.orderButton.setGeometry(QtCore.QRect(290, 310, 221, 31))
        self.orderButton.setObjectName("orderButton")
        self.tableChoiceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tableChoiceComboBox.setGeometry(QtCore.QRect(220, 310, 61, 21))
        self.tableChoiceComboBox.setObjectName("tableChoiceComboBox")
        self.amountLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.amountLabel_2.setGeometry(QtCore.QRect(170, 310, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.amountLabel_2.setFont(font)
        self.amountLabel_2.setObjectName("amountLabel_2")
        cartWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(cartWindow)
        self.statusbar.setObjectName("statusbar")
        cartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(cartWindow)
        QtCore.QMetaObject.connectSlotsByName(cartWindow)

    def retranslateUi(self, cartWindow):
        _translate = QtCore.QCoreApplication.translate
        cartWindow.setWindowTitle(_translate("cartWindow", "Кошик"))
        self.amountLabel.setText(_translate("cartWindow", "TextLabel"))
        self.orderButton.setText(_translate("cartWindow", "Оформити замовлення"))
        self.amountLabel_2.setText(_translate("cartWindow", "Столик"))
