# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cookWindow(object):
    def setupUi(self, cookWindow):
        cookWindow.setObjectName("cookWindow")
        cookWindow.resize(338, 458)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        cookWindow.setFont(font)
        self.label_4 = QtWidgets.QLabel(cookWindow)
        self.label_4.setGeometry(QtCore.QRect(490, 20, 31, 31))
        self.label_4.setStyleSheet("background-image:url(cart.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.ordersList = QtWidgets.QListWidget(cookWindow)
        self.ordersList.setGeometry(QtCore.QRect(20, 40, 301, 281))
        self.ordersList.setObjectName("ordersList")
        self.label_5 = QtWidgets.QLabel(cookWindow)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 301, 31))
        self.label_5.setObjectName("label_5")
        self.sendToKitchenButton = QtWidgets.QPushButton(cookWindow)
        self.sendToKitchenButton.setGeometry(QtCore.QRect(20, 330, 301, 51))
        self.sendToKitchenButton.setObjectName("sendToKitchenButton")
        self.OpenTheScheduleCook = QtWidgets.QPushButton(cookWindow)
        self.OpenTheScheduleCook.setGeometry(QtCore.QRect(70, 400, 211, 41))
        self.OpenTheScheduleCook.setObjectName("OpenTheScheduleCook")

        self.retranslateUi(cookWindow)
        QtCore.QMetaObject.connectSlotsByName(cookWindow)

    def retranslateUi(self, cookWindow):
        _translate = QtCore.QCoreApplication.translate
        cookWindow.setWindowTitle(_translate("cookWindow", "Користувач"))
        self.label_5.setText(_translate("cookWindow", "Список замовлень очікують"))
        self.sendToKitchenButton.setText(_translate("cookWindow", "Приготовлено!"))
        self.OpenTheScheduleCook.setText(_translate("cookWindow", "Розклад роботи"))
