# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guestWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guestWindow(object):
    def setupUi(self, guestWindow):
        guestWindow.setObjectName("guestWindow")
        guestWindow.resize(633, 416)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        guestWindow.setFont(font)
        self.label = QtWidgets.QLabel(guestWindow)
        self.label.setGeometry(QtCore.QRect(350, 20, 181, 31))
        self.label.setObjectName("label")
        self.dishesList = QtWidgets.QListWidget(guestWindow)
        self.dishesList.setGeometry(QtCore.QRect(10, 80, 301, 261))
        self.dishesList.setObjectName("dishesList")
        self.label_2 = QtWidgets.QLabel(guestWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(guestWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:grey")
        self.label_3.setObjectName("label_3")
        self.searchLineEdit = QtWidgets.QLineEdit(guestWindow)
        self.searchLineEdit.setGeometry(QtCore.QRect(10, 360, 301, 31))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.line = QtWidgets.QFrame(guestWindow)
        self.line.setGeometry(QtCore.QRect(320, 30, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dishDetailsTextEdit = QtWidgets.QTextEdit(guestWindow)
        self.dishDetailsTextEdit.setGeometry(QtCore.QRect(350, 80, 261, 251))
        self.dishDetailsTextEdit.setStyleSheet("background: rgba(0,0,255,0%)")
        self.dishDetailsTextEdit.setObjectName("dishDetailsTextEdit")

        self.retranslateUi(guestWindow)
        QtCore.QMetaObject.connectSlotsByName(guestWindow)

    def retranslateUi(self, guestWindow):
        _translate = QtCore.QCoreApplication.translate
        guestWindow.setWindowTitle(_translate("guestWindow", "Гість"))
        self.label.setText(_translate("guestWindow", "Подробиця:"))
        self.label_2.setText(_translate("guestWindow", "Список страв"))
        self.label_3.setText(_translate("guestWindow", "Клацніть двічі для перегляду детальної інформації"))
        self.searchLineEdit.setPlaceholderText(_translate("guestWindow", "Пошук страви"))
        self.dishDetailsTextEdit.setHtml(_translate("guestWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
