# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(313, 148)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        loginForm.setFont(font)
        self.usernameLineEdit = QtWidgets.QLineEdit(loginForm)
        self.usernameLineEdit.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(loginForm)
        self.passwordLineEdit.setGeometry(QtCore.QRect(10, 60, 291, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginButton = QtWidgets.QPushButton(loginForm)
        self.loginButton.setGeometry(QtCore.QRect(10, 100, 131, 31))
        self.loginButton.setObjectName("loginButton")
        self.registrationButton = QtWidgets.QPushButton(loginForm)
        self.registrationButton.setGeometry(QtCore.QRect(150, 100, 151, 31))
        self.registrationButton.setObjectName("registrationButton")

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "Авторизация"))
        self.usernameLineEdit.setPlaceholderText(_translate("loginForm", "Логін"))
        self.passwordLineEdit.setPlaceholderText(_translate("loginForm", "Пароль"))
        self.loginButton.setText(_translate("loginForm", "Увійти "))
        self.registrationButton.setText(_translate("loginForm", "Реєстрація"))
