# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registrationForm(object):
    def setupUi(self, registrationForm):
        registrationForm.setObjectName("registrationForm")
        registrationForm.resize(313, 247)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        registrationForm.setFont(font)
        self.nameLineEdit = QtWidgets.QLineEdit(registrationForm)
        self.nameLineEdit.setGeometry(QtCore.QRect(10, 10, 291, 31))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.surnameLineEdit = QtWidgets.QLineEdit(registrationForm)
        self.surnameLineEdit.setGeometry(QtCore.QRect(10, 50, 291, 31))
        self.surnameLineEdit.setObjectName("surnameLineEdit")
        self.registrationButton = QtWidgets.QPushButton(registrationForm)
        self.registrationButton.setGeometry(QtCore.QRect(10, 170, 291, 31))
        self.registrationButton.setObjectName("registrationButton")
        self.passwordLineEdit = QtWidgets.QLineEdit(registrationForm)
        self.passwordLineEdit.setGeometry(QtCore.QRect(10, 130, 291, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.usernameLineEdit = QtWidgets.QLineEdit(registrationForm)
        self.usernameLineEdit.setGeometry(QtCore.QRect(10, 90, 291, 31))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.infoLabel = QtWidgets.QLabel(registrationForm)
        self.infoLabel.setGeometry(QtCore.QRect(10, 210, 291, 31))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")

        self.retranslateUi(registrationForm)
        QtCore.QMetaObject.connectSlotsByName(registrationForm)

    def retranslateUi(self, registrationForm):
        _translate = QtCore.QCoreApplication.translate
        registrationForm.setWindowTitle(_translate("registrationForm", "Регістрація"))
        self.nameLineEdit.setPlaceholderText(_translate("registrationForm", "Iм\'я"))
        self.surnameLineEdit.setPlaceholderText(_translate("registrationForm", "Прізвище"))
        self.registrationButton.setText(_translate("registrationForm", "Зареєструватися"))
        self.passwordLineEdit.setPlaceholderText(_translate("registrationForm", "Пароль"))
        self.usernameLineEdit.setPlaceholderText(_translate("registrationForm", "Логін"))
