# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffLoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_staffLoginForm(object):
    def setupUi(self, staffLoginForm):
        staffLoginForm.setObjectName("staffLoginForm")
        staffLoginForm.resize(313, 105)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        staffLoginForm.setFont(font)
        self.keyLineEdit = QtWidgets.QLineEdit(staffLoginForm)
        self.keyLineEdit.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.keyLineEdit.setObjectName("keyLineEdit")
        self.loginButton = QtWidgets.QPushButton(staffLoginForm)
        self.loginButton.setGeometry(QtCore.QRect(10, 60, 291, 31))
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(staffLoginForm)
        QtCore.QMetaObject.connectSlotsByName(staffLoginForm)

    def retranslateUi(self, staffLoginForm):
        _translate = QtCore.QCoreApplication.translate
        staffLoginForm.setWindowTitle(_translate("staffLoginForm", "Авторизация"))
        self.keyLineEdit.setPlaceholderText(_translate("staffLoginForm", "Введіть код співробітника"))
        self.loginButton.setText(_translate("staffLoginForm", "Увійти "))
