# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableReserveWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tableReserveForm(object):
    def setupUi(self, tableReserveForm):
        tableReserveForm.setObjectName("tableReserveForm")
        tableReserveForm.resize(341, 257)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        tableReserveForm.setFont(font)
        self.label_4 = QtWidgets.QLabel(tableReserveForm)
        self.label_4.setGeometry(QtCore.QRect(490, 20, 31, 31))
        self.label_4.setStyleSheet("background-image:url(cart.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(tableReserveForm)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 321, 31))
        self.comboBox.setObjectName("comboBox")
        self.timeEdit = QtWidgets.QTimeEdit(tableReserveForm)
        self.timeEdit.setGeometry(QtCore.QRect(10, 50, 321, 41))
        self.timeEdit.setObjectName("timeEdit")
        self.infoLabel = QtWidgets.QLabel(tableReserveForm)
        self.infoLabel.setGeometry(QtCore.QRect(10, 190, 321, 51))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.reserveButton = QtWidgets.QPushButton(tableReserveForm)
        self.reserveButton.setGeometry(QtCore.QRect(140, 100, 191, 31))
        self.reserveButton.setObjectName("reserveButton")
        self.tableChoiceComboBox = QtWidgets.QComboBox(tableReserveForm)
        self.tableChoiceComboBox.setGeometry(QtCore.QRect(60, 100, 71, 31))
        self.tableChoiceComboBox.setObjectName("tableChoiceComboBox")
        self.tableLabel = QtWidgets.QLabel(tableReserveForm)
        self.tableLabel.setGeometry(QtCore.QRect(10, 105, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tableLabel.setFont(font)
        self.tableLabel.setObjectName("tableLabel")
        self.dateEdit = QtWidgets.QDateEdit(tableReserveForm)
        self.dateEdit.setGeometry(QtCore.QRect(10, 50, 321, 41))
        self.dateEdit.setObjectName("dateEdit")
        self.showReservesTableButton = QtWidgets.QPushButton(tableReserveForm)
        self.showReservesTableButton.setGeometry(QtCore.QRect(70, 140, 211, 31))
        self.showReservesTableButton.setObjectName("showReservesTableButton")

        self.retranslateUi(tableReserveForm)
        QtCore.QMetaObject.connectSlotsByName(tableReserveForm)

    def retranslateUi(self, tableReserveForm):
        _translate = QtCore.QCoreApplication.translate
        tableReserveForm.setWindowTitle(_translate("tableReserveForm", "Бронювання"))
        self.reserveButton.setText(_translate("tableReserveForm", "Забронювати"))
        self.tableLabel.setText(_translate("tableReserveForm", "Столик"))
        self.showReservesTableButton.setText(_translate("tableReserveForm", "Бронювання"))
