# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userWindow(object):
    def setupUi(self, userWindow):
        userWindow.setObjectName("userWindow")
        userWindow.resize(633, 416)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        userWindow.setFont(font)
        self.label = QtWidgets.QLabel(userWindow)
        self.label.setGeometry(QtCore.QRect(350, 20, 181, 31))
        self.label.setObjectName("label")
        self.dishesList = QtWidgets.QListWidget(userWindow)
        self.dishesList.setGeometry(QtCore.QRect(10, 80, 301, 261))
        self.dishesList.setObjectName("dishesList")
        self.label_2 = QtWidgets.QLabel(userWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(userWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:grey")
        self.label_3.setObjectName("label_3")
        self.searchLineEdit = QtWidgets.QLineEdit(userWindow)
        self.searchLineEdit.setGeometry(QtCore.QRect(10, 360, 301, 31))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.line = QtWidgets.QFrame(userWindow)
        self.line.setGeometry(QtCore.QRect(320, 30, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dishDetailsTextEdit = QtWidgets.QTextEdit(userWindow)
        self.dishDetailsTextEdit.setGeometry(QtCore.QRect(350, 80, 261, 251))
        self.dishDetailsTextEdit.setStyleSheet("background: rgba(0,0,255,0%)")
        self.dishDetailsTextEdit.setObjectName("dishDetailsTextEdit")
        self.addToCartButton = QtWidgets.QPushButton(userWindow)
        self.addToCartButton.setGeometry(QtCore.QRect(410, 340, 191, 41))
        self.addToCartButton.setObjectName("addToCartButton")
        self.label_4 = QtWidgets.QLabel(userWindow)
        self.label_4.setGeometry(QtCore.QRect(490, 20, 31, 31))
        self.label_4.setStyleSheet("background-image:url(cart.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.cartButton = QtWidgets.QPushButton(userWindow)
        self.cartButton.setGeometry(QtCore.QRect(530, 20, 81, 31))
        self.cartButton.setObjectName("cartButton")
        self.dishesCountSpinBox = QtWidgets.QSpinBox(userWindow)
        self.dishesCountSpinBox.setGeometry(QtCore.QRect(351, 341, 41, 41))
        self.dishesCountSpinBox.setMinimum(1)
        self.dishesCountSpinBox.setObjectName("dishesCountSpinBox")
        self.reserveButton = QtWidgets.QPushButton(userWindow)
        self.reserveButton.setGeometry(QtCore.QRect(480, 383, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.reserveButton.setFont(font)
        self.reserveButton.setObjectName("reserveButton")

        self.retranslateUi(userWindow)
        QtCore.QMetaObject.connectSlotsByName(userWindow)

    def retranslateUi(self, userWindow):
        _translate = QtCore.QCoreApplication.translate
        userWindow.setWindowTitle(_translate("userWindow", "Користувач"))
        self.label.setText(_translate("userWindow", "Подробиця:"))
        self.label_2.setText(_translate("userWindow", "Список страв"))
        self.label_3.setText(_translate("userWindow", "Клацніть двічі для перегляду детальної інформації"))
        self.searchLineEdit.setPlaceholderText(_translate("userWindow", "Пошук страви"))
        self.dishDetailsTextEdit.setHtml(_translate("userWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.addToCartButton.setText(_translate("userWindow", "Додати"))
        self.cartButton.setText(_translate("userWindow", "Кошик"))
        self.reserveButton.setText(_translate("userWindow", "Забронювати"))
