# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waiterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_waiterWindow(object):
    def setupUi(self, waiterWindow):
        waiterWindow.setObjectName("waiterWindow")
        waiterWindow.resize(976, 444)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        waiterWindow.setFont(font)
        self.label = QtWidgets.QLabel(waiterWindow)
        self.label.setGeometry(QtCore.QRect(350, 20, 181, 31))
        self.label.setObjectName("label")
        self.dishesList = QtWidgets.QListWidget(waiterWindow)
        self.dishesList.setGeometry(QtCore.QRect(10, 80, 301, 261))
        self.dishesList.setObjectName("dishesList")
        self.label_2 = QtWidgets.QLabel(waiterWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(waiterWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:grey")
        self.label_3.setObjectName("label_3")
        self.searchLineEdit = QtWidgets.QLineEdit(waiterWindow)
        self.searchLineEdit.setGeometry(QtCore.QRect(10, 360, 301, 31))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.line = QtWidgets.QFrame(waiterWindow)
        self.line.setGeometry(QtCore.QRect(320, 30, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dishDetailsTextEdit = QtWidgets.QTextEdit(waiterWindow)
        self.dishDetailsTextEdit.setGeometry(QtCore.QRect(350, 80, 261, 251))
        self.dishDetailsTextEdit.setStyleSheet("background: rgba(0,0,255,0%)")
        self.dishDetailsTextEdit.setObjectName("dishDetailsTextEdit")
        self.addToCartButton = QtWidgets.QPushButton(waiterWindow)
        self.addToCartButton.setGeometry(QtCore.QRect(410, 340, 191, 41))
        self.addToCartButton.setObjectName("addToCartButton")
        self.label_4 = QtWidgets.QLabel(waiterWindow)
        self.label_4.setGeometry(QtCore.QRect(490, 20, 31, 31))
        self.label_4.setStyleSheet("background-image:url(cart.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.cartButton = QtWidgets.QPushButton(waiterWindow)
        self.cartButton.setGeometry(QtCore.QRect(530, 20, 81, 31))
        self.cartButton.setObjectName("cartButton")
        self.dishesCountSpinBox = QtWidgets.QSpinBox(waiterWindow)
        self.dishesCountSpinBox.setGeometry(QtCore.QRect(351, 341, 41, 41))
        self.dishesCountSpinBox.setMinimum(1)
        self.dishesCountSpinBox.setObjectName("dishesCountSpinBox")
        self.line_2 = QtWidgets.QFrame(waiterWindow)
        self.line_2.setGeometry(QtCore.QRect(630, 20, 20, 361))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget = QtWidgets.QTabWidget(waiterWindow)
        self.tabWidget.setGeometry(QtCore.QRect(650, 20, 321, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.sendToKitchenButton = QtWidgets.QPushButton(self.tab)
        self.sendToKitchenButton.setGeometry(QtCore.QRect(10, 270, 221, 41))
        self.sendToKitchenButton.setObjectName("sendToKitchenButton")
        self.ordersList = QtWidgets.QListWidget(self.tab)
        self.ordersList.setGeometry(QtCore.QRect(10, 10, 301, 251))
        self.ordersList.setObjectName("ordersList")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ordersList_2 = QtWidgets.QListWidget(self.tab_2)
        self.ordersList_2.setGeometry(QtCore.QRect(10, 10, 301, 251))
        self.ordersList_2.setObjectName("ordersList_2")
        self.paidButton = QtWidgets.QPushButton(self.tab_2)
        self.paidButton.setGeometry(QtCore.QRect(10, 270, 191, 41))
        self.paidButton.setObjectName("paidButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.OpenTheScheduleButton = QtWidgets.QPushButton(waiterWindow)
        self.OpenTheScheduleButton.setGeometry(QtCore.QRect(410, 400, 191, 31))
        self.OpenTheScheduleButton.setObjectName("OpenTheScheduleButton")

        self.retranslateUi(waiterWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(waiterWindow)

    def retranslateUi(self, waiterWindow):
        _translate = QtCore.QCoreApplication.translate
        waiterWindow.setWindowTitle(_translate("waiterWindow", "Користувач"))
        self.label.setText(_translate("waiterWindow", "Подробиця:"))
        self.label_2.setText(_translate("waiterWindow", "Список страв"))
        self.label_3.setText(_translate("waiterWindow", "Клацніть двічі для перегляду детальної інформації"))
        self.searchLineEdit.setPlaceholderText(_translate("waiterWindow", "Пошук страви"))
        self.dishDetailsTextEdit.setHtml(_translate("waiterWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.addToCartButton.setText(_translate("waiterWindow", "Додавши"))
        self.cartButton.setText(_translate("waiterWindow", "Кошик"))
        self.sendToKitchenButton.setText(_translate("waiterWindow", "Передати на кухню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("waiterWindow", "Оформлений"))
        self.paidButton.setText(_translate("waiterWindow", "Оплачений"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("waiterWindow", "До оплати"))
        self.OpenTheScheduleButton.setText(_translate("waiterWindow", "Розклад роботи"))
